# Identity Setting
# ================
# you should change this to suit your own preference.

title:       Polar                      #TODO title of this site
description: White-Clean Jekyll Theme   #TODO short description
logo:        "/images/logo.png"         #TODO logo, recommended 256x256

baseurl: "/polar"                       #TODO leaves blank if already root
url:     "https://neizod.github.io"     #TODO canonical url w/ protocol

author: neizod                          #TODO single author only
rights: All Right Reserved              #TODO rights statement

google_analytics:                       #TODO e.g. U-8152342-4
disqus:                                 #TODO if polar.disqus.com, then polar


# Layout Setting
# ==============
# you may change this to suit your own preference.

timezone:  Asia/Bangkok                 #TODO post time offset
show_time: true                         #TODO show time alongside date?

older_left: false                       #TODO show older link on leftside?
paginate:   3                           #TODO nos of excerpt post per page
mathjax:    true                        #TODO if true, write $ with \\$


# Engine Setting
# ==============
# you shouldn't change this unless you really know what you're doing.

paginate_path: "/posts/page:num"

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      article: true
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: projects
    values:
      layout: project

sass:
  sass_dir: "_sass/"
  style: compressed

exclude:
  - README.md
  - LICENSE.txt

gems:
  - jekyll-sitemap
  - jekyll-paginate
