# Identity Setting
# ================
# you should change this to suit your own preference.

title:       Polar                      #TODO title of this site
description: White-Clean Jekyll Theme   #TODO short description
logo:        "/images/logo.png"         #TODO logo, recommended 256x256

baseurl: "/polar"                       #TODO leaves blank if already root
url:     "https://neizod.github.io"     #TODO canonical url w/ protocol

author: neizod                          #TODO single author only
rights: All Right Reserved              #TODO rights statement

google_analytics:                       #TODO e.g. U-8152342-4
disqus:                                 #TODO if polar.disqus.com, then polar


# Layout Setting
# ==============
# you may change this to suit your own preference.

timezone:  Asia/Bangkok                 #TODO post time offset
show_time: true                         #TODO show time alongside date?

older_left: false                       #TODO show older link on leftside?
paginate:   3                           #TODO nos of excerpt post per page
mathjax:    true                        #TODO if true, write $ with \\$

theme:
  palette:   north-pole                 #TODO set these to null to define your
  highlight: trac                       #TODO own color palette and highlight

text:
  latest_post:  Latest Post             #TODO settings for top-right label
  feature_post: Feature Post            #TODO of excerpt post on index page
  feature_proj: Feature Project         #TODO _______________________________
  proj_demo:    Live Demo!              #TODO settings for project demo/source
  proj_source:  Source Code             #TODO _______________________________
  left_sym:     «                       #TODO settings for left/right symbol
  right_sym:    »                       #TODO _______________________________
  at_page:      "Page: "                #TODO settings for pagination text,
  of_page:      " of "                  #TODO example layout render:
  prev_page:    Prev                    #TODO <ls,prev>  <at>2<of>3  <next,rs>
  next_page:    Next                    #TODO _______________________________
  title_sep:    "|"                     #TODO <post-title> <sep> <site-title>
  read_more:    Read More               #TODO read more text


# Engine Setting
# ==============
# you shouldn't change this unless you really know what you're doing.

paginate_path: "/posts/page:num"

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      article: true
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: projects
    values:
      layout: project

sass:
  sass_dir: "_sass/"
  style: compressed

exclude:
  - README.md
  - LICENSE.txt

gems:
  - jekyll-sitemap
  - jekyll-paginate
