# Identity Setting
# ================
# you should change this to suit your own preference.

title: Polar
description: White-Clean Jekyll Theme
baseurl: "/polar"
url: "https://neizod.github.io"

# also don't forget to check:
# - `/favicon.png`
# - `/images/logo.png`


# Layout Setting
# ==============
# you may change this to suit your own preference.

timezone: Asia/Bangkok
mathjax: true


# Engine Setting
# ==============
# you shouldn't change this unless you really know what you're doing.

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post

sass:
  sass_dir: "_sass/"
  style: compressed
