# Identity Setting
# ================
# you should change this to suit your own preference.

title: Polar
description: White-Clean Jekyll Theme
baseurl: "/polar"
url: "https://neizod.github.io"

author: neizod
rights: All Right Reserved

google_analytics:

# also don't forget to check:
# - `/favicon.png`
# - `/images/logo.png`


# Layout Setting
# ==============
# you may change this to suit your own preference.

timezone: Asia/Bangkok
paginate: 5
mathjax: true

# Engine Setting
# ==============
# you shouldn't change this unless you really know what you're doing.

paginate_path: "/blog/page:num"

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      article: true
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: projects
    values:
      layout: project

sass:
  sass_dir: "_sass/"
  style: compressed

gems:
  - jekyll-paginate
